use crate::core::error::{JarvisError, Result};
use crate::core::is_test_environment;
use crate::tools::Tool;
use crate::ui::theme::load_omarchy_theme;
use async_trait::async_trait;
use regex::Regex;
use serde_json::{json, Value};
use std::env;
use std::fs;
use std::path::PathBuf;
use std::process::Stdio;
use std::sync::Arc;
use tokio::process::Command;
use tracing::{debug, info};

pub struct ResearchManager {
    cache_dir: PathBuf,
    kitty_bin: Option<PathBuf>,
    foot_bin: Option<PathBuf>,
    nvim_bin: PathBuf,
}

impl Default for ResearchManager {
    fn default() -> Self {
        Self::new()
    }
}

impl ResearchManager {
    pub fn new() -> Self {
        let home = env::var("HOME").unwrap_or_else(|_| ".".to_string());
        let cache_dir = PathBuf::from(&home).join(".cache/jarvis/research");
        let _ = fs::create_dir_all(&cache_dir);

        let kitty_bin = which::which("kitty").ok();
        let foot_bin = which::which("foot").ok();
        let nvim_bin = which::which("nvim").unwrap_or_else(|_| PathBuf::from("nvim"));

        Self {
            cache_dir,
            kitty_bin,
            foot_bin,
            nvim_bin,
        }
    }

    /// Generates a filesystem-friendly slug from title
    pub fn slugify(title: &str) -> String {
        let re = Regex::new(r"[^\w\s-]").unwrap();
        let cleaned = re.replace_all(title.trim(), "").to_lowercase();
        let slug = cleaned.split_whitespace().collect::<Vec<&str>>().join("_");
        if slug.is_empty() {
            "research_report".to_string()
        } else {
            slug.chars().take(40).collect()
        }
    }

    /// Formats and saves research markdown to cache directory
    pub fn save_markdown(&self, title: &str, content: &str) -> Result<PathBuf> {
        let slug = Self::slugify(title);
        let now = chrono::Local::now();
        let timestamp = now.format("%Y%m%d_%H%M%S").to_string();
        let filename = format!("{slug}_{timestamp}.md");
        let filepath = self.cache_dir.join(filename);

        let formatted_content = if content.starts_with('#') {
            format!(
                "{content}\n\n---\n*Jarvis AI Research Assistant • {} • Press `q` or `Ctrl+C` to close this window.*\n",
                now.format("%B %d, %Y %I:%M %p")
            )
        } else {
            format!(
                "# {title}\n\n*Generated by Jarvis on {}*\n\n---\n\n{content}\n\n---\n*Press `q` or `Ctrl+C` to close this window.*\n",
                now.format("%B %d, %Y %I:%M %p")
            )
        };

        fs::write(&filepath, formatted_content).map_err(|e| {
            JarvisError::Other(format!("Failed to save research markdown file: {e}"))
        })?;

        info!("Saved research markdown to: {:?}", filepath);
        Ok(filepath)
    }

    /// Spawns a floating terminal window running Neovim displaying the markdown file
    pub async fn open_in_floating_neovim(&self, title: &str, filepath: &PathBuf) -> Result<String> {
        let file_str = filepath.to_string_lossy().to_string();
        let window_title = format!("󰚩 Jarvis Research: {title}");
        let theme = load_omarchy_theme();

        debug!(
            "Launching floating Neovim popup for '{}' at {:?} (theme bg: {})",
            title, filepath, theme.dark_background
        );

        if is_test_environment() {
            return Ok(format!(
                "Opened research on '{title}' in floating Neovim popup."
            ));
        }

        let nvim_args = [
            "-R", // Read-only view
            "-c",
            "set wrap linebreak nonumber norelativenumber foldlevel=99 conceallevel=2",
            "-c",
            "nnoremap <buffer> q :q!<CR>",
            "-c",
            "nnoremap <buffer> <C-c> :q!<CR>",
            &file_str,
        ];

        if let Some(ref kitty) = self.kitty_bin {
            let mut cmd = Command::new(kitty);
            cmd.process_group(0);
            cmd.arg("--class")
                .arg("TUI.float")
                .arg("-T")
                .arg(&window_title)
                .arg("-o")
                .arg("initial_window_width=980")
                .arg("-o")
                .arg("initial_window_height=700")
                .arg("-o")
                .arg("window_padding_width=18")
                .arg("-o")
                .arg("remember_window_size=no")
                .arg("-o")
                .arg("confirm_os_window_close=0")
                .arg("-o")
                .arg(format!("background={}", theme.dark_background))
                .arg("-o")
                .arg(format!("foreground={}", theme.foreground))
                .arg(&self.nvim_bin)
                .args(nvim_args);

            cmd.stdout(Stdio::null()).stderr(Stdio::null());
            cmd.spawn().map_err(|e| {
                JarvisError::Other(format!("Failed to spawn kitty floating window: {e}"))
            })?;
            return Ok(format!(
                "Opened research on '{title}' in floating Neovim popup."
            ));
        }

        if let Some(ref foot) = self.foot_bin {
            let mut cmd = Command::new(foot);
            cmd.process_group(0);
            cmd.arg("--app-id")
                .arg("TUI.float")
                .arg("-T")
                .arg(&window_title)
                .arg("-w")
                .arg("980x700")
                .arg(&self.nvim_bin)
                .args(nvim_args);

            cmd.stdout(Stdio::null()).stderr(Stdio::null());
            cmd.spawn().map_err(|e| {
                JarvisError::Other(format!("Failed to spawn foot floating window: {e}"))
            })?;
            return Ok(format!(
                "Opened research on '{title}' in floating Neovim popup."
            ));
        }

        // Generic xdg-terminal-exec fallback
        if let Ok(term) = which::which("xdg-terminal-exec") {
            let mut cmd = Command::new(term);
            cmd.process_group(0);
            cmd.arg("--app-id=TUI.float")
                .arg(&self.nvim_bin)
                .args(nvim_args);
            cmd.stdout(Stdio::null()).stderr(Stdio::null());
            cmd.spawn()
                .map_err(|e| JarvisError::Other(format!("Failed to spawn terminal: {e}")))?;
            return Ok(format!(
                "Opened research on '{title}' in floating Neovim popup."
            ));
        }

        // Direct nvim execution fallback
        let mut cmd = Command::new(&self.nvim_bin);
        cmd.process_group(0);
        cmd.args(nvim_args);
        cmd.stdout(Stdio::null()).stderr(Stdio::null());
        cmd.spawn()
            .map_err(|e| JarvisError::Other(format!("Failed to launch nvim: {e}")))?;

        Ok(format!("Opened research on '{title}' in Neovim."))
    }

    /// Save content to markdown and immediately open in floating Neovim window
    pub async fn display_research(&self, title: &str, content: &str) -> Result<String> {
        let filepath = self.save_markdown(title, content)?;
        self.open_in_floating_neovim(title, &filepath).await
    }
}

// -----------------------------------------------------------------------------
// Tool Implementations
// -----------------------------------------------------------------------------

pub struct DisplayResearchInNeovimTool {
    manager: Arc<ResearchManager>,
}

impl DisplayResearchInNeovimTool {
    pub fn new(manager: Arc<ResearchManager>) -> Self {
        Self { manager }
    }
}

#[async_trait]
impl Tool for DisplayResearchInNeovimTool {
    fn name(&self) -> &'static str {
        "display_research_in_neovim"
    }

    fn description(&self) -> &'static str {
        "Display in-depth research, study notes, technical explanations, or reports in a floating Neovim popup window on the desktop as formatted Markdown."
    }

    fn parameters_schema(&self) -> Value {
        json!({
            "type": "OBJECT",
            "properties": {
                "title": {
                    "type": "STRING",
                    "description": "Short, clear title for the research topic (e.g. 'Quantum Computing Architecture', 'Rust 2024 Edition Features', 'WireGuard Setup Guide')."
                },
                "content": {
                    "type": "STRING",
                    "description": "The complete, detailed research report formatted in clean Markdown (with headings #, ##, bullet points, technical details, code blocks, and conclusions)."
                }
            },
            "required": ["title", "content"]
        })
    }

    async fn execute(&self, args: Value) -> Result<String> {
        let title = args["title"].as_str().ok_or_else(|| {
            JarvisError::ToolParameter(
                "display_research_in_neovim".into(),
                "title is required".into(),
            )
        })?;
        let content = args["content"].as_str().ok_or_else(|| {
            JarvisError::ToolParameter(
                "display_research_in_neovim".into(),
                "content is required".into(),
            )
        })?;

        self.manager.display_research(title, content).await
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_slugify() {
        assert_eq!(
            ResearchManager::slugify("Quantum Computing 2026"),
            "quantum_computing_2026"
        );
        assert_eq!(
            ResearchManager::slugify("WireGuard / VPN Setup!"),
            "wireguard_vpn_setup"
        );
        assert_eq!(ResearchManager::slugify(""), "research_report");
    }

    #[test]
    fn test_save_markdown() {
        let mgr = ResearchManager::new();
        let path = mgr
            .save_markdown("Test Topic", "## Details\nSome research content")
            .unwrap();
        assert!(path.exists());
        let text = fs::read_to_string(&path).unwrap();
        assert!(text.contains("Some research content"));
        assert!(text.contains("Press `q` or `Ctrl+C` to close this window"));
        let _ = fs::remove_file(path);
    }
}
